package voxlink.shared.protocol;

// Enum representing all possible response types from the server
public enum ResponseType {
    // Authentication Responses
    AUTH_LOGIN_SUCCESS,
    AUTH_LOGIN_FAILURE,
    AUTH_REGISTER_SUCCESS,
    AUTH_REGISTER_FAILURE,
    AUTH_LOGOUT_SUCCESS,
    AUTH_LOGOUT_FAILURE,
    AUTH_PROFILE_DATA,

    // Workspace Responses
    WORKSPACE_LIST_DATA,
    WORKSPACE_CREATE_SUCCESS,
    WORKSPACE_CREATE_FAILURE,
    WORKSPACE_JOIN_SUCCESS,
    WORKSPACE_JOIN_FAILURE,
    WORKSPACE_LEAVE_SUCCESS,
    WORKSPACE_LEAVE_FAILURE,
    WORKSPACE_DELETE_SUCCESS,
    WORKSPACE_DELETE_FAILURE,
    WORKSPACE_INFO_DATA,
    WORKSPACE_BROADCAST_UPDATE,

    // Channel Responses
    CHANNEL_LIST_DATA,
    CHANNEL_CREATE_SUCCESS,
    CHANNEL_CREATE_FAILURE,
    CHANNEL_JOIN_SUCCESS,
    CHANNEL_JOIN_FAILURE,
    CHANNEL_LEAVE_SUCCESS,
    CHANNEL_LEAVE_FAILURE,
    CHANNEL_DELETE_SUCCESS,
    CHANNEL_DELETE_FAILURE,
    CHANNEL_HISTORY_DATA,
    CHANNEL_BROADCAST_UPDATE,

    // Messaging Responses
    MESSAGE_SEND_SUCCESS,
    MESSAGE_SEND_FAILURE,
    MESSAGE_EDIT_SUCCESS,
    MESSAGE_EDIT_FAILURE,
    MESSAGE_DELETE_SUCCESS,
    MESSAGE_DELETE_FAILURE,
    MESSAGE_BROADCAST,
    MESSAGE_UPDATE_BROADCAST,
    MESSAGE_TYPING_BROADCAST,

    // File Responses
    FILE_UPLOAD_START_ACK,
    FILE_UPLOAD_CHUNK_ACK,
    FILE_UPLOAD_COMPLETE_ACK,
    FILE_UPLOAD_FAILURE,
    FILE_DOWNLOAD_DATA,
    FILE_DOWNLOAD_COMPLETE,
    FILE_DOWNLOAD_FAILURE,
    FILE_DELETE_SUCCESS,
    FILE_DELETE_FAILURE,
    FILE_BROADCAST,

    // User Presence Responses
    USER_STATUS_UPDATED,
    USER_ONLINE_LIST_DATA,
    USER_PRESENCE_BROADCAST,
    USER_TYPING_BROADCAST,

    // Role Responses
    ROLE_ASSIGN_SUCCESS,
    ROLE_ASSIGN_FAILURE,
    ROLE_REVOKE_SUCCESS,
    ROLE_REVOKE_FAILURE,
    ROLE_PERMISSIONS_DATA,

    // Invite Responses
    INVITE_CREATE_SUCCESS,
    INVITE_CREATE_FAILURE,
    INVITE_VALIDATE_SUCCESS,
    INVITE_VALIDATE_FAILURE,

    // Audit Responses
    AUDIT_LOG_DATA,
    AUDIT_EXPORT_SUCCESS,
    AUDIT_EXPORT_FAILURE,

    // Heartbeat Responses
    HEARTBEAT_PONG,

    // Error and Status
    ERROR_GENERAL,
    ERROR_UNAUTHORIZED,
    ERROR_RATE_LIMITED,
    CONNECTION_CLOSED,

    // RMI-Specific Responses
    RMI_SERVER_STATS,
    RMI_REMOTE_CALL_SUCCESS,
    RMI_REMOTE_CALL_FAILURE
}